export const TEXT_EXTRACTION_MODEL = 'gemini-3-flash-preview';
export const PLAN_GENERATION_MODEL = 'gemini-3-flash-preview';
export const EMBEDDING_MODEL = 'gemini-embedding-2-preview';
export const CHUNK_SIZE = 512;       // approximate tokens
export const CHUNK_OVERLAP = 100;    // approximate tokens
export const TOP_N_CHUNKS = 4;
export const TEACHING_CHAT_MODEL = 'gemini-3-flash-preview';
export const SUMMARIZATION_MODEL = 'gemini-3-flash-preview';
export const SUMMARIZATION_TOKEN_THRESHOLD = 30000;
export const MIN_UNSUMMARIZED_MESSAGES = 2;
export const RATE_LIMIT_MESSAGES_PER_MINUTE = 10;
